name: Run Microservice Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Make mvnw executable
        run: |
          chmod +x ./User_microservice/mvnw
          chmod +x ./Task_microservice/mvnw
          chmod +x ./List_microservice/mvnw
          chmod +x ./Reporting_microservice/mvnw
          chmod +x ./Feedback_microservice/mvnw
          chmod +x ./Competition_microservice/mvnw
          chmod +x ./Database_microservice/mvnw
          chmod +x ./API_Gateway/mvnw

      - name: Build all microservices
        run: |
              ./User_microservice/mvnw clean package -DskipTests
              ./Task_microservice/mvnw clean package -DskipTests
              ./List_microservice/mvnw clean package -DskipTests
              ./Reporting_microservice/mvnw clean package -DskipTests
              ./Feedback_microservice/mvnw clean package -DskipTests
              ./Competition_microservice/mvnw clean package -DskipTests
              ./Database_microservice/mvnw clean package -DskipTests
              ./API_Gateway/mvnw clean package -DskipTests




      - name: Run unit tests in all microservices
        run: |
          mvn -f User_microservice/pom.xml test -Dsurefire.printSummary=true
          mvn -f Task_microservice/pom.xml test -Dsurefire.printSummary=true
          mvn -f List_microservice/pom.xml test -Dsurefire.printSummary=true
          mvn -f Reporting_microservice/pom.xml test -Dsurefire.printSummary=true
          mvn -f Feedback_microservice/pom.xml test -Dsurefire.printSummary=true
          mvn -f Competition_microservice/pom.xml test -Dsurefire.printSummary=true

    
